
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_with_postgres'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_with_postgres'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  dbt_with_postgres:
    #example:
      #+schema: example
      #+materialized: view

    # raw:
    #   +schema: raw
    #   +materialized: view
    
    # Config indicated by + and applies to all files under models/staging/jaffle_shop/
    # The +schema config creates a schema in the database for the models using the schema
    # in profiles.yml and the schema name  here in the config (jaffle_shop_staging)
    staging:
      +schema: staging
      +materialized: view
    
    intermediate:
      +schema: intermediate
      +materialized: table

    marts:
      +schema: marts
      +materialized: table

    demo:
      legacy:
        +schema: legacy
        +materialized: table
      staging:
        +schema: migration_staging
        +materialized: view
      intermediate:
        +schema: migration_intermediate
        +materialized: table
      marts:
        +schema: migration_marts
        +materialized: table
      audits:
        +schema: audits
        +materialized: view
